In [1]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [2]:
%cd /content/drive/My Drive/panda

/content/drive/My Drive/panda

#**Pandas Time Series Analysis Tutorial: Handling Holidays**

In [3]:
import pandas as pd
df = pd.read_csv("aapl_no_dates.csv")
df

      Open    High     Low   Close    Volume
0   153.17  153.33  152.22  153.18  16404088
1   153.58  155.45  152.89  155.45  27770715
2   154.34  154.45  153.46  153.93  25331662
3   153.90  155.81  153.78  154.45  26624926
4   155.02  155.98  154.48  155.37  21069647
5   155.25  155.54  154.40  154.99  21250798
6   155.19  155.19  146.02  148.98  64882657
7   145.74  146.09  142.51  145.42  72307330
8   147.16  147.45  145.15  146.59  34165445
9   147.50  147.50  143.84  145.16  31531232
10  143.32  144.48  142.21  144.29  32165373
11  143.78  144.50  142.20  142.27  50361093
12  143.66  146.74  143.66  146.34  32541404
13  146.87  146.87  144.94  145.01  24900073
14  145.52  146.07  144.61  145.87  21265751
15  145.77  146.70  145.12  145.63  19106294
16  145.13  147.16  145.11  146.28  35439389
17  147.17  148.28  145.38  145.82  25692361
18  145.01  146.16  143.62  143.73  24761891
19  144.49  146.11  143.16  145.83  22082432
20  144.71  145.13  142.28  143.68  31499368
21  144.45  144.96  143.78  144.02  23024107

In [4]:
rng = pd.date_range(start="6/30/2017", end="7/31/2017", freq='B')
rng

DatetimeIndex(['2017-06-30', '2017-07-03', '2017-07-04', '2017-07-05',
               '2017-07-06', '2017-07-07', '2017-07-10', '2017-07-11',
               '2017-07-12', '2017-07-13', '2017-07-14', '2017-07-17',
               '2017-07-18', '2017-07-19', '2017-07-20', '2017-07-21',
               '2017-07-24', '2017-07-25', '2017-07-26', '2017-07-27',
               '2017-07-28', '2017-07-31'],
              dtype='datetime64[ns]', freq='B')

**here Using 'B' frequency is not going to help because 4th July was holiday and 'B' is not taking that into account. It only accounts for weekends**

#**Using CustomBusinessDay to generate US holidays calendar frequency**

In [5]:
from pandas.tseries.holiday import USFederalHolidayCalendar
from pandas.tseries.offsets import CustomBusinessDay

us_cal = CustomBusinessDay(calendar=USFederalHolidayCalendar())

rng = pd.date_range(start="6/30/2017",end="8/01/2017", freq=us_cal)
rng

DatetimeIndex(['2017-06-30', '2017-07-03', '2017-07-05', '2017-07-06',
               '2017-07-07', '2017-07-10', '2017-07-11', '2017-07-12',
               '2017-07-13', '2017-07-14', '2017-07-17', '2017-07-18',
               '2017-07-19', '2017-07-20', '2017-07-21', '2017-07-24',
               '2017-07-25', '2017-07-26', '2017-07-27', '2017-07-28',
               '2017-07-31', '2017-08-01'],
              dtype='datetime64[ns]', freq='C')

In [6]:
df.set_index(rng,inplace=True)
df.head()

              Open    High     Low   Close    Volume
2017-06-30  153.17  153.33  152.22  153.18  16404088
2017-07-03  153.58  155.45  152.89  155.45  27770715
2017-07-05  154.34  154.45  153.46  153.93  25331662
2017-07-06  153.90  155.81  153.78  154.45  26624926
2017-07-07  155.02  155.98  154.48  155.37  21069647

#**We can define our own calendar using AbstractHolidayCalendar as shown below.**
**USFederalHolidayCalendar is the only calendar available in pandas library and it serves as an example for those who want to write their own custom calendars.**

In [7]:
from pandas.tseries.holiday import AbstractHolidayCalendar, nearest_workday, Holiday
class myCalendar(AbstractHolidayCalendar):
    rules = [
        Holiday('My Birth Day', month=4, day=14),       #, observance=nearest_workday),
    ]
    
my_bday = CustomBusinessDay(calendar=myCalendar())
rng=pd.date_range('4/1/2017','5/3/2017',freq=my_bday)
rng

DatetimeIndex(['2017-04-03', '2017-04-04', '2017-04-05', '2017-04-06',
               '2017-04-07', '2017-04-10', '2017-04-11', '2017-04-12',
               '2017-04-13', '2017-04-17', '2017-04-18', '2017-04-19',
               '2017-04-20', '2017-04-21', '2017-04-24', '2017-04-25',
               '2017-04-26', '2017-04-27', '2017-04-28', '2017-05-01',
               '2017-05-02', '2017-05-03'],
              dtype='datetime64[ns]', freq='C')

#**CustomBusinessDay**
**Weekend in egypt is Friday and Saturday. Sunday is just a normal weekday and you can handle this custom week schedule using CystomBysinessDay with weekmask as shown below**

In [9]:
egypt_weekdays = "Sun Mon Tue Wed Thu"

b = CustomBusinessDay(weekmask=egypt_weekdays)

pd.date_range(start="7/1/2017",periods=22,freq=b)

DatetimeIndex(['2017-07-02', '2017-07-03', '2017-07-04', '2017-07-05',
               '2017-07-06', '2017-07-09', '2017-07-10', '2017-07-11',
               '2017-07-12', '2017-07-13', '2017-07-16', '2017-07-17',
               '2017-07-18', '2017-07-19', '2017-07-20', '2017-07-23',
               '2017-07-24', '2017-07-25', '2017-07-26', '2017-07-27',
               '2017-07-30', '2017-07-31'],
              dtype='datetime64[ns]', freq='C')

#**We can also add holidays to this custom business day frequency**

In [ ]:
b = CustomBusinessDay(holidays=['2017-07-04', '2017-07-10'], weekmask=egypt_weekdays)

pd.date_range(start="7/1/2017",periods=22,freq=b)

DatetimeIndex(['2017-07-02', '2017-07-03', '2017-07-05', '2017-07-06',
               '2017-07-09', '2017-07-11', '2017-07-12', '2017-07-13',
               '2017-07-16', '2017-07-17', '2017-07-18', '2017-07-19',
               '2017-07-20', '2017-07-23', '2017-07-24', '2017-07-25',
               '2017-07-26', '2017-07-27', '2017-07-30', '2017-07-31',
               '2017-08-01', '2017-08-02'],
              dtype='datetime64[ns]', freq='C')

#**Mathematical operations on date object using custom business day**

In [ ]:
from datetime import datetime
dt = datetime(2017,7,9)
dt

datetime.datetime(2017, 7, 9, 0, 0)

In [ ]:
dt + 1*b

Timestamp('2017-07-11 00:00:00')