In [1]:
import pandas as pd
import sqlalchemy

#check this video if you want to read database records into pandas framework and write it back

[link text](https://)https://www.youtube.com/watch?v=M-4EpNdlSuY&ab_channel=codebasics

# in above video we had covered

1.   pd.read_sql_table
2.   pd.read_sql_query
3.   df.to_sql
4.   pd.read_sql(which is just a wrapper for first two methods