#**using csv**

In [15]:
import pandas as pd
import io

In [16]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [18]:
%cd /content/drive/My Drive/panda/

/content/drive/My Drive/panda

In [19]:
df = pd.read_csv("Weather_data.csv")
df

          day  temperature  windspeed   event
0  01-01-2017           32          6    Rain
1  02-01-2017           35          5   Sunny
2  03-01-2017           28          8    snow
3  04-01-2017           26          9   Windy
4  05-01-2017           39          2  Moisty

#**Using excel**

In [ ]:
df=pd.read_excel('Weather_data.xlsx')
df

         day  temperature  windspeed   event
0 2017-01-01           32          6    Rain
1 2017-01-02           35          5   Sunny
2 2017-01-03           28          8    snow
3 2017-01-04           26          9   Windy
4 2017-01-05           39          2  Moisty

#**Using dictionary**

In [ ]:
weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature': [32,35,28],
    'windspeed': [6,7,2],
    'event': ['Rain', 'Sunny', 'Snow']
}
df = pd.DataFrame(weather_data)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

#**Using tuples list**

In [ ]:
weather_data = [
    ('1/1/2017',32,6,'Rain'),  # this is the first row
    ('1/2/2017',35,7,'Sunny'),  # this is the second row and so on
    ('1/3/2017',28,2,'Snow')
]
df = pd.DataFrame(data=weather_data, columns=['day','temperature','windspeed','event']) # here we have to give the columns name
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

#**Using list of dictionaries**

In [ ]:
weather_data = [
    {'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
    {'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
    {'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'},
    
]
df = pd.DataFrame(data=weather_data, columns=['day','temperature','windspeed','event'])
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

#**some more methods to creatde a dataframe:==>> [link text](https://)https://pandas.pydata.org/docs/user_guide/io.html**