#**python is a python module which makes data science effective and efficient**

**process of cleaning the data is called data munging/wrangling**

**Dataframe is a main object in panda. It is used to represent data with rows and columns similar to excel spreadsheet**

#**using python dictionary to create a dataframe**

In [ ]:
import pandas as pd 
wheather_data={
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}
df = pd.DataFrame(wheather_data)

df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

#**getting the size of the dataframe**

In [ ]:
print(df.shape)
rows,columns=df.shape
print("no of rows is:",rows)
print("no of cols:",columns)

(6, 4)
no of rows is: 6
no of cols: 4

#**using head(no.of rows you want to print(N)) to print first N rows of the dataframe**

In [9]:
print(df.head(3))
print("\nWithout passing any argument in the head function \n")
print(df.head())

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

Without passing any argument in the head function

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

#**using tail(no.of rows you want to print(N)) to print last N rows of the dataframe**

In [12]:
print(df.tail())
print("\n                                 Printing last 3 rows:")
df.tail(3)

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

                                 Printing last 3 rows:

        day  temperature  windspeed  event
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

#**slicing and indexing is similar to a list**

In [17]:
print(df[1:4])
print()
print()
print()
print(df[0:5])
print()
print()

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow



        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

#**printing columns of dataframe**

In [18]:
print(df.columns)

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [19]:
df.day

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [20]:
df['event']   # df.event both are same

0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
Name: event, dtype: object

#**using type function to determine the type of any columns**

In [21]:
type(df['day'])

pandas.core.series.Series

In [22]:
type(df.day)

pandas.core.series.Series

#**printing one or more columns of the dataframe**

In [27]:
print(df[['day','temperature']])
print()

print(df[['day','event','temperature']])

        day  temperature
0  1/1/2017           32
1  1/2/2017           35
2  1/3/2017           28
3  1/4/2017           24
4  1/5/2017           32
5  1/6/2017           31

        day  event  temperature
0  1/1/2017   Rain           32
1  1/2/2017  Sunny           35
2  1/3/2017   Snow           28
3  1/4/2017   Snow           24
4  1/5/2017   Rain           32
5  1/6/2017  Sunny           31

#**operations of DataFrame**

In [28]:
df['temperature'].max()

35

In [29]:
df['temperature'].mean()

30.333333333333332

In [30]:
df['temperature'].min()

24

In [32]:
df['temperature'].std()

3.8297084310253524

In [33]:
df['event'].max() # But mean() won't work since data type is string

'Sunny'

#**using describe() method**

In [34]:
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

#**some sql query like Conditional select the data in your dataframe**

In [36]:
df[df['temperature']>=32]

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
4  1/5/2017           32          4   Rain

In [38]:
df[df.temperature==df.temperature.max()]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [37]:
df[df['temperature']==df['temperature'].max()]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

#**To print required columns for the conditional select of the data**

In [39]:
df[['day','temperature']][df['temperature']==df['temperature'].max()]

        day  temperature
1  1/2/2017           35

#**There are many methods for pandas among which some are discussed above and here is the link for all of the methods of the panda methods**

Google pandas series operations to find out list of all operations:-[link text](https://)http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.html

#**set_index() and reset_index() methods**

In [40]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [47]:
df.set_index('day')  # here the original dataframe is not modified

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

 **Modifying the index in the original dataframe**

In [48]:
df.set_index('day', inplace=True)   
df

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [49]:
df.loc['1/2/2017']

temperature       35
windspeed          7
event          Sunny
Name: 1/2/2017, dtype: object

#**Resetting the index in  the original Dataframe**

In [50]:
df.reset_index(inplace=True)
df.head()

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

#**setting index = event in the original rested dataframe**

In [51]:
df.set_index('event',inplace=True) # this is kind of building a hash map using event as a key
df

            day  temperature  windspeed
event
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           31          2

In [53]:
df.loc['Snow']

            day  temperature  windspeed
event
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7

In [54]:
df.reset_index(inplace=True)
df.head()

   event       day  temperature  windspeed
0   Rain  1/1/2017           32          6
1  Sunny  1/2/2017           35          7
2   Snow  1/3/2017           28          2
3   Snow  1/4/2017           24          7
4   Rain  1/5/2017           32          4